// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wndgogkhezqvihyrqasn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InduZGdvZ2toZXpxdmloeXJxYXNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNTgxNDEsImV4cCI6MjA2NTczNDE0MX0.of-Oyakv7E5MhwSL-yt-Dqj2NNnrDI1r4p0VWUmdK_A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);